### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by nikokreissl** [nikokreissl/fifa23-tracker#30]
## Value Proposition

**As a** developer
**I want to** see clean code
**so that** everything is in place (understandable) for other developers, is semantically correct, etc
​

## Description

- component, function and var names to be clearly understandable
- items that can be outsourced to be outsourced
- code to be not repeated
​

## Acceptance Criteria

- [x] code is semantically correct
- [x] all names are clear
- [x] code is as "DRY" as possible
      ​

## Tasks

- [x] check each component and page for semantic items and correct if needed (e.g. back button)
- [x] check location and names of styled components, move and correct them if needed
- [x] check if e.g. create and edit form can be used as component 

## Complexity

M
